services:
  app-db:
    image: postgres
    container_name: netku-db

    volumes:
      - db-dir:/var/lib/postgresql/data

    networks:
      - backend-net

    hostname: postgresql

    ports:
      - 5432:5432

    env_file:
      - .env

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 10

  app-backend:
    container_name: netku-backend
    build:
      context: src/backend

    volumes:
      - cert-dir:/etc/cert:ro
      - xray-dir:/etc/xray
      - xray-log-dir:/etc/xray/log

    networks:
      - backend-net

    ports:
      - 443:443

    env_file:
      - .env

    depends_on:
      app-db:
        condition: service_healthy

volumes:
  cert-dir:
    external: true
  xray-dir:
    external: true
  xray-log-dir:
    external: true
  db-dir:
    external: true

networks:
  backend-net:
    name: backend-net
