services:
  app-db:
    image: postgres
    container_name: netku-db

    ports:
      - 5432:5432

    volumes:
      - db-dir:/var/lib/postgresql/data

    env_file:
      - .env

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 10

  app-backend:
    container_name: netku-backend
    build:
      context: src/backend

    volumes:
      - cert-dir:/etc/cert:ro
      - xray-dir:/etc/xray

    env_file:
      - .env

    ports:
      - 443:443

    depends_on:
      app-db:
        condition: service_healthy

volumes:
  cert-dir:
    external: true
  xray-dir:
    external: true
  xray-log-dir:
    external: true
  db-dir:
    external: true
