services:
  db:
    container_name: netku-db
    image: postgres

    volumes:
      - db-dir:/var/lib/postgresql/data

    networks:
      - netku-net

    hostname: postgresql

    ports:
      - 5432:5432

    env_file:
      - .env

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 5s
      retries: 10

  xray:
    container_name: netku-xray
    build:
      context: services/xray

    volumes:
      - cert-dir:/etc/cert:ro
      - xray-log-dir:/etc/xray/log

    networks:
      - netku-net

    ports:
      - 443:443

    env_file:
      - .env

  assistant:
    container_name: netku-assistant
    build:
      context: services/assistant

    volumes:
      - cert-dir:/etc/cert:ro
      - xray-log-dir:/etc/xray/log

    networks:
      - netku-net

    env_file:
      - .env

    depends_on:
      db:
        condition: service_healthy

  server:
    container_name: netku-server
    build:
      context: services/server
      args:
        PORT:
        DOMAIN:
        XRAY_FALLBACK_PORT:


    volumes:
      - cert-dir:/etc/cert:ro
      - nginx-html:/usr/share/nginx/html

    networks:
      - netku-net

    ports:
      - 80:80

    env_file:
      - .env

  landing:
    build:
      context: services/landing

    volumes:
      - nginx-html:/app/dist

volumes:
  cert-dir:
    external: true
  xray-log-dir:
    external: true
  db-dir:
    external: true
  nginx-html:


networks:
  netku-net:
    name: netku-net
