services:
  landing:
    container_name: netku-landing
    restart: always
    build:
      context: clients/landing

    volumes:
      - nginx-html:/app/dist

  # region services
  auth:
    container_name: netku-auth
    restart: always
    build:
      context: .
      dockerfile: docker/auth.Dockerfile

    volumes:
      - cert-dir:/etc/cert:ro

    networks:
      - netku-network

  user:
    container_name: netku-user
    restart: always
    build:
      context: .
      dockerfile: docker/user.Dockerfile

    volumes:
      - cert-dir:/etc/cert:ro

    networks:
      - netku-network
  # endregion

volumes:
  cert-dir:
    external: true
  xray-log-dir:
    external: true

networks:
  netku-network:
    name: netku-network
