"""Adding proxy subscription to user

Revision ID: 6b330bf463fa
Revises: 8f81a875074f
Create Date: 2024-08-04 19:25:29.008691

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6b330bf463fa"
down_revision: Union[str, None] = "8f81a875074f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workers", sa.Column("proxy_subscription", sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workers", "proxy_subscription")
    # ### end Alembic commands ###
