"""Changing info fields, renaming table

Revision ID: ae688b85ea1a
Revises: be1f2dbfe4aa
Create Date: 2025-02-27 10:54:36.643755

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ae688b85ea1a"
down_revision: Union[str, None] = "be1f2dbfe4aa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "proxy_infos",
        sa.Column("uuid", sa.Uuid(), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("addr", sa.String(), nullable=False),
        sa.Column("running", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("proxy_info")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "proxy_info",
        sa.Column("uuid", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "last_update", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("synced", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("running", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="proxy_info_pkey"),
    )
    op.drop_table("proxy_infos")
    # ### end Alembic commands ###
