[tool.ruff]
target-version = "py311"

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
