name: assistant-ci
on:
  pull_request:
    branches:
      - master
    types: [synchronize, opened]

jobs:
  build-and-test:
    name: Build and test assistant
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dev dependencies
        working-directory: services/assistant
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements-dev.txt
      - name: Run Ruff
        working-directory: services/assistant
        run: |
          ruff check .
          ruff format --check .
      - name: Run pytest tests
        working-directory: services/assistant
        run: python -m pytest
