name: Build and test assistant

on:
  pull_request:
    branches:
      - master
    types: [synchronize, opened]

jobs:
  build:
    name: Build assistant
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        working-directory: services/assistant
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt
          pip install --no-cache-dir ruff
      - name: Run Ruff
        working-directory: services/assistant
        run: |
          ruff check .
          ruff format --check .
      # TODO: Make tests
