# Deploys only on closed pull request to master with label **assistant** and **enhancement**.
name: assistant-cd
on:
  push:
    branches:
      - master

jobs:
  run-common:
    uses: ./.github/workflows/common.yml

  deploy:
    name: Deploy assistant
    if: |
      contains(fromJson(needs.run-common.outputs.pr_data).labels.*.name, 'assistant') && 
      contains(fromJson(needs.run-common.outputs.pr_data).labels.*.name, 'enhancement')

    runs-on: ubuntu-latest
    needs: run-common
    environment: deploying

    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Restart assistant
        run: ssh -p ${{ secrets.SSH_PORT }} root@${{ secrets.SERVER_IP }} 'cd /root/netku && git pull && python manage.py -r assistant'
