name: Common utils for actions

on:
  workflow_call:
    outputs:
      pr_labels:
        description: "Pull request labels"
        value: ${{ jobs.pr-data.outputs.pr_labels }}

jobs:
  pr-data:
    name: common
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read

    outputs:
      pr_labels: ${{ fromJson(steps.get_pr_data.outputs.result).title }}

    steps:
      - uses: actions/github-script@v7
        id: get_pr_data
        with:
          script: |
            return (
              await github.rest.repos.listPullRequestsAssociatedWithCommit({
                commit_sha: context.sha,
                owner: context.repo.owner,
                repo: context.repo.repo,
              })
            ).data[0];
