on:
  pull_request:
    branches:
      - master
    types: [synchronize, opened]

jobs:
  build-and-test:
    name: Build landing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.2.x"
      - name: Install dependencies
        working-directory: services/landing
        run: npm install
      - name: Run build
        working-directory: services/landing
        run: npm run build
      # TODO: Make tests [e2e, unit]
