# Deploys only on closed pull request to master with label **landing**.
name: landing-cd
on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  data:
    uses: ./.github/workflows/common.yml

  deploy:
    name: Deploy landing
    if: |
      contains( github.event.pull_request.labels.*.name, 'landing') && 
      github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: data
    environment: deploying

    steps:
      - name: echo data
        run: echo '${{ fromJson(needs.data.outputs.pr_labels) }}'

      # - name: Set up SSH
      #   run: |
      #     mkdir -p ~/.ssh
      #     echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
      #     chmod 600 ~/.ssh/id_rsa
      #     ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      # - name: Restart landing
      #   run: ssh -p ${{ secrets.SSH_PORT }} root@${{ secrets.SERVER_IP }} 'cd /root/netku && git pull && cd .. && ./restart_landing.sh'
