name: landing-ci
on:
  pull_request:
    branches:
      - master
    types: [synchronize, opened]
  workflow_dispatch:

jobs:
  build:
    name: Build landing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.2.x"

      - name: Install dependencies
        working-directory: services/landing
        run: npm install

      - name: Run build
        working-directory: services/landing
        run: npm run build
      - name: Run prettier
        working-directory: services/landing
        run: npx -a prettier -c .

  test:
    name: Test landing
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.2.x"

      - name: Install dependencies
        working-directory: services/landing
        run: npm install --include=dev
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Run Playwright tests
        working-directory: services/landing
        run: npx playwright test
