name: lint-check
on: push
jobs:
  build-assistant:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        working-directory: ./assistant

        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt
          pip install --no-cache-dir ruff
      - name: Run Ruff
        working-directory: ./assistant
        run: |
          ruff check .
          ruff format --check .
