name: lint-check
on: push
jobs:
  build-assistant:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setip Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        working-directory: ./services/assistant

        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt
          pip install --no-cache-dir ruff
      - name: Run Ruff
        working-directory: ./services/assistant
        run: |
          ruff check .
          ruff format --check .

  build-go:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.22.6"]

    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          # Semantic version range syntax or exact version of Go
          go-version: "1.22.6"
      - name: Install dependencies
        working-directory: ./services/xray
        run: go mod download
      - name: Run build
        run: go build .
