name: python-services-ci
on:
  pull_request:
    branches:
      - master
    types: [synchronize, opened]

jobs:
  build-and-test:
    name: Build and test python service
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build_services: [
            "common/python",
            "services/user",
            "services/proxy",
            "services/auth",
          ] # Services

        test_services: ["services/user", "services/auth"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dev dependencies
        working-directory: ${{ matrix.build_services }}
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements-dev.txt
      - name: Run Ruff
        working-directory: ${{ matrix.build_services }}
        run: |
          ruff check .
          ruff format --check .
      - name: Run pytest tests
        working-directory: ${{ matrix.test_services }}
        run: python -m pytest
