# Deploys only on closed pull request to master
# with labels **enhancement** or **bug**.

name: xray-cd
on:
  push:
    # branches:
    #   - master

jobs:
  run-common:
    uses: ./.github/workflows/common.yml

  build-and-push:
    name: Build and push xray image
      contains(fromJson(needs.run-common.outputs.pr_data).labels.*.name, 'xray') &&
      (
      contains(fromJson(needs.run-common.outputs.pr_data).labels.*.name, 'enhancement') ||
      contains(fromJson(needs.run-common.outputs.pr_data).labels.*.name, 'bug')
      )

    runs-on: ubuntu-latest
    needs: run-common
    environment: staging-deploy

    steps:
      - uses: actions/checkout@v4

      # - name: Log in to registry
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ${{ secrets.REGISTRY_URL }}
      #     username: ${{ secrets.REGISTRY_USERNAME }}
      #     password: ${{ secrets.REGISTRY_PASSWORD }}

      # - name: Build and push image
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     file: docker/xray.Dockerfile
      #     push: true
      #     tags: |
      #       ${{secrets.REGISTRY_URL}}/netku/xray:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: staging-deploy

    steps:
      - name: Deploy via SSH action
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.PROJECT_DIR }}
